"""
NeuroFocus Constants.
"""

# Face detection thresholds
PITCH_OFFSET = 5.0
PITCH_THRESHOLD = 0.0
PITCH_THRESHOLD_TOP = 30.0
YAW_THRESHOLD = 40.0

# Fatigue detection
EAR_THRESHOLD_LOW = 0.25
EAR_THRESHOLD_HIGH = 0.30
MAR_THRESHOLD = 0.5

# Posture detection
POSTURE_TIME_TRIGGER = 1.0
COOLDOWN_POSTURE_EVENT = 1.0
COOLDOWN_YAWING_EVENT = 2.0

# Gesture control
GESTURE_SMOOTHING = 10
GESTURE_CLICK_THRESHOLD = 0.055
GESTURE_CLICK_COOLDOWN = 0.3

# Database
DATABASE_NAME = "session_data.db"

# Video
DEFAULT_CAMERA = 0
FRAME_WIDTH = 640
FRAME_HEIGHT = 480
FPS = 30
